(function(){
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='bb_admin_hash_v3',GH='bb_gh_v3',SITE='bb_site_v3';let ps=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const enc=s=>btoa(unescape(encodeURIComponent(s)));
async function sha(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function setMsg(id,t,ok=false){const e=$(id);if(!e)return;e.textContent=t;e.className='form-msg '+(ok?'ok':'')}
function gh(){try{return JSON.parse(sessionStorage.getItem(GH)||'{}')}catch{return {}}}
function loadSite(){try{const s=JSON.parse(localStorage.getItem(SITE)||'{}');$('#siteName').value=s.name||'BanglaBazar';$('#siteLogo').value=s.logo||'';$('#themeColor').value=s.theme||'#1565c0';$('#buttonColor').value=s.button||'#1565c0';$('#heroTitleInput').value=s.heroTitle||'BanglaBazar';$('#heroTextInput').value=s.heroText||'পছন্দের পণ্য সহজেই খুঁজুন এবং কার্টে যোগ করুন।'}catch{}}
async function enter(){const p=$('#adminPassword').value.trim();if(!p)return setMsg('#adminMsg','Admin password দিন।');let h=localStorage.getItem(KEY);if(!h){h=await sha(p);localStorage.setItem(KEY,h);sessionStorage.setItem('bb_admin_ok','1');openPanel();return}if(await sha(p)===h){sessionStorage.setItem('bb_admin_ok','1');openPanel()}else setMsg('#adminMsg','Password সঠিক নয়।')}
function openPanel(){$('#adminGate').classList.add('hidden');$('#adminPanel').classList.remove('hidden');loadSite();loadProducts()}
async function loadProducts(){try{const r=await fetch('data/products.json?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();const j=await r.json();ps=j.products||[]}catch{ps=[]}$('#adminProductList').innerHTML=ps.map(p=>`<div class="admin-product"><b>${esc(p.title)}</b><span>${esc(p.id)}</span><button data-edit="${esc(p.id)}">Edit</button></div>`).join('')||'<p class="muted">কোনো পণ্য নেই।</p>'}
function githubArgs(){const x=gh();return{u:$('#ghUser').value.trim()||x.user,r:$('#ghRepo').value.trim()||x.repo,t:$('#ghToken').value.trim()||x.token,b:$('#ghBranch').value.trim()||x.branch||'main'}}
async function api(path,opts={}){const g=githubArgs();if(!g.u||!g.r||!g.t)throw Error('GitHub username, repository এবং token দিন।');const url='https://api.github.com/repos/'+encodeURIComponent(g.u)+'/'+encodeURIComponent(g.r)+'/contents/'+path;const r=await fetch(url,{...opts,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+g.t,'Content-Type':'application/json'}});if(!r.ok)throw Error('GitHub API '+r.status+': '+await r.text());return r.json()}
async function put(path,content,message){let old=null;try{old=await api(path)}catch(e){if(!String(e.message).includes('GitHub API 404'))throw e}const body={message,content:enc(content),branch:githubArgs().b};if(old?.sha)body.sha=old.sha;return api(path,{method:'PUT',body:JSON.stringify(body)})}
function collect(){const raw=$('#pId').value.trim().toLowerCase();const id=raw.replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'');return{id,slug:id,title:$('#pTitle').value.trim(),category:$('#pCategory').value.trim(),price:Number($('#pPrice').value||0),oldPrice:Number($('#pOldPrice').value||0),image:$('#pImage').value.trim(),images:$('#pImages').value.split('\n').map(x=>x.trim()).filter(Boolean),youtube:$('#pYoutube').value.split('\n').map(x=>x.trim()).filter(Boolean),description:'content/'+id+'.md'}}
async function publish(){try{const p=collect();if(!p.id||!p.title)throw Error('English Product ID/slug এবং পণ্যের নাম দিন।');if(!/^[a-z0-9-]+$/.test(p.id))throw Error('Product ID শুধু English letter, number এবং hyphen ব্যবহার করুন।');const data=await BB.loadProducts(true);const arr=data.filter(x=>String(x.id)!==p.id);arr.push(p);await put('data/products.json',JSON.stringify({version:3,products:arr},null,2),'Update product '+p.id);await put('content/'+p.id+'.md',$('#pDescription').value,'Update description '+p.id);await put('products/'+p.id+'.html',productPageFor(p),'Publish product page '+p.id);setMsg('#publishMsg','পণ্য সফলভাবে GitHub-এ publish হয়েছে।',true);await loadProducts()}catch(e){setMsg('#publishMsg',e.message)}}
function productPageFor(){return `<!doctype html><html lang="bn"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Product — BanglaBazar</title><link rel="stylesheet" href="../assets/style.css"></head><body><header class="topbar"><a class="back" href="../index.html">←</a><a class="brand" href="../index.html"><span class="brand-logo">B</span><span id="brandName">BanglaBazar</span></a><div class="top-actions"><a href="../search.html">⌕</a><a href="../wishlist.html">♡</a><a class="cart-link" href="../cart.html">🛒<b id="cartCount">0</b></a></div></header><main class="page product-page"><div id="productLoading" class="loading-card">পণ্য লোড হচ্ছে…</div><div id="productError" class="error-card hidden"><h2>পণ্য পাওয়া যায়নি</h2><p id="productErrorText" class="muted"></p><a class="btn" href="../index.html">হোমে ফিরে যান</a></div><article id="productView" class="hidden"><div id="productGallery"></div><h1 id="productTitle"></h1><div class="price-row"><strong id="productPrice"></strong><del id="productOldPrice"></del></div><div id="productMeta"></div><div class="product-actions"><button class="btn" id="buyNow">এখনই কিনুন</button><button class="btn secondary" id="addCart">কার্টে যোগ করুন</button><button class="icon-btn" id="addWishlist">♡</button></div><p class="buy-note">এখনই কিনুন চাপলে আপনার Firebase প্রোফাইলের তথ্য ও পণ্যের লিংকসহ WhatsApp খুলবে।</p><div id="youtubeBox"></div><section class="description"><div id="descriptionContent"></div></section><section id="relatedSection"><h2>আপনার আরও পছন্দ হতে পারে</h2><div id="relatedGrid" class="product-grid compact"></div></section></article></main><nav class="bottom-nav"><a href="../index.html">⌂<span>হোম</span></a><a href="../search.html">⌕<span>সার্চ</span></a><a class="nav-cart" href="../cart.html">🛒<i id="bottomCartCount">0</i><span>কার্ট</span></a><a href="../wishlist.html">♡<span>উইশলিস্ট</span></a><a href="../profile.html">◉<span>প্রোফাইল</span></a></nav><script src="https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js"></script><script src="https://www.gstatic.com/firebasejs/10.14.1/firebase-auth-compat.js"></script><script src="https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore-compat.js"></script><script src="../js/config.js"></script><script src="../js/app.js"></script><script>document.addEventListener('DOMContentLoaded',()=>BB.initProductPage());</script></body></html>`}
function edit(id){const p=ps.find(x=>String(x.id)===String(id));if(!p)return;$('#pId').value=p.id;$('#pTitle').value=p.title||'';$('#pCategory').value=p.category||'';$('#pPrice').value=p.price||'';$('#pOldPrice').value=p.oldPrice||'';$('#pImage').value=p.image||'';$('#pImages').value=(p.images||[]).join('\n');$('#pYoutube').value=(p.youtube||[]).join('\n');fetch(p.description+'?v='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.text():'').then(t=>$('#pDescription').value=t).catch(()=>{});window.scrollTo({top:0,behavior:'smooth'})}
async function testGithub(){try{const g=githubArgs();if(!g.u||!g.r||!g.t)throw Error('Username, repository এবং token দিন।');const r=await api('');setMsg('#ghMsg','GitHub connection সফল। Repository: '+(r.full_name||g.u+'/'+g.r),true)}catch(e){setMsg('#ghMsg',e.message)}}
function init(){
  if(sessionStorage.getItem('bb_admin_ok')==='1')openPanel();
  $('#adminEnter').onclick=enter;
  $('#saveGithub').onclick=()=>{const g=githubArgs();if(!g.u||!g.r||!g.t)return setMsg('#ghMsg','সব GitHub তথ্য দিন।');sessionStorage.setItem(GH,JSON.stringify(g));setMsg('#ghMsg','GitHub connection এই session-এ save হয়েছে।',true)};
  $('#testGithub').onclick=testGithub;
  $('#clearGithub').onclick=()=>{sessionStorage.removeItem(GH);$('#ghToken').value='';setMsg('#ghMsg','Session token মুছে ফেলা হয়েছে।',true)};
  $('#publishProduct').onclick=publish;
  $('#adminProductList').onclick=e=>{const b=e.target.closest('[data-edit]');if(b)edit(b.dataset.edit)};
  $$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.admin-tab').forEach(x=>x.classList.add('hidden'));$('#tab-'+b.dataset.tab).classList.remove('hidden')});
  $('#saveSite').onclick=()=>{const s={name:$('#siteName').value.trim()||'BanglaBazar',logo:$('#siteLogo').value.trim(),theme:$('#themeColor').value,button:$('#buttonColor').value,heroTitle:$('#heroTitleInput').value.trim()||'BanglaBazar',heroText:$('#heroTextInput').value.trim()};localStorage.setItem(SITE,JSON.stringify(s));BB.applySite();setMsg('#siteMsg','সাইট কাস্টমাইজেশন এই browser-এ save হয়েছে।',true)};
  const g=gh();$('#ghUser').value=g.user||'';$('#ghRepo').value=g.repo||'';$('#ghBranch').value=g.branch||'main';loadSite();
}
document.addEventListener('DOMContentLoaded',init);
})();
